######################################################################
# Automatically generated by qmake (3.0) Per May 18 21:03:36 2017
######################################################################

TEMPLATE = app
TARGET = hw3
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
